package com.niit.ZealTechBackEnd.Model;

import java.util.UUID;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

@Entity
@Table
@Component
public class Product {
	@Id
	private String productId;
	private String productName;
	private String productDescription;
	private int productQuantity;
	private double productPrice;
	// For Multipart FileUpload
	private String imageName;
	@Transient
	private MultipartFile pimg;

	public MultipartFile getPimg() {
		return pimg;
	}

	public void setPimg(MultipartFile pimg) {
		this.pimg = pimg;
	}

	public String getImageName() {
		return imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	public Product() {
		// TODO Auto-generated constructor stub
		this.productId = "PROD" + UUID.randomUUID().toString().substring(30).toUpperCase();
	}

	@ManyToOne
	@JoinColumn(name = "catId")
	private Category category;

//	@OneToOne
//	@JoinColumn(name = "cartItemsId")
//	private CartItems cartItems;

//	public CartItems getCartItems() {
//		return cartItems;
//	}
//
//	public void setCartItems(CartItems cartItems) {
//		this.cartItems = cartItems;
//	}

	// Generated By @ManyToOne for Category
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne
	@JoinColumn(name = "supplierId")
	private Supplier supplier;

	// Getters And Setters Generated by @ManyToOne for Supplier

	public Supplier getSupplier() {
		return supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	// Getters and setters generated for the attributes
	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductDescription() {
		return productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public int getProductQuantity() {
		return productQuantity;
	}

	public void setProductQuantity(int productQuantity) {
		this.productQuantity = productQuantity;
	}

	public double getProductPrice() {
		return productPrice;
	}

	public void setProductPrice(double productPrice) {
		this.productPrice = productPrice;
	}

	
	}
